apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stage
  namespace: dvb-csdp
spec:
  project: default
  source:
    repoURL: https://github.com/dustinvanbuskirk/promotion-repository-example.git
    targetRevision: HEAD
    path: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true